version: '3'
services:
  nginx:
    ports:
      - "3000:80"
  node-app:
    build: 
      context: .
      args:
        NODE_ENV: development
    volumes:
      - ./:/app
      - /app/node_modules
    environment:
    # Below varibales store data to proces.ENV
      - NODE_ENV=development
      - MONGO_USER=blogger
      - MONGO_PASSWORD=blog2022
      - SESSION_SECRET=secret
    command: npm run dev
  mongo:
    environment:
      - MONGO_INITDB_ROOT_USERNAME=blogger
      - MONGO_INITDB_ROOT_PASSWORD=blog2022